# Nested sampling parameters
nested_sampling:
  n_live: 100
  n_params: 5
  n_delete: 1
  num_mcmc_steps_multiplier: 5  # Will be multiplied by n_params
  max_iterations: 10000

# Prior bounds
prior_bounds:
  z:
    min: 0.001
    max: 0.2
  t0:
    min: 58000.0
    max: 59000.0
  x0:
    min: -6.0  # log10(1e-6)
    max: -3.0  # log10(1e-3)
  x1:
    min: -3.0
    max: 3.0
  c:
    min: -0.3
    max: 0.3

# Prior distributions
prior_distributions:
  t0:
    type: normal
    loc: 58520.0
    scale: 2.0
  x1:
    type: normal
    loc: 1.5
    scale: 1.0
  c:
    type: normal
    loc: 0.2
    scale: 0.2 