fix_z: true
nested_sampling:
  max_iterations: 10000
  n_delete: 1
  n_live: 100
  n_params: 5
  num_mcmc_steps_multiplier: 5
prior_bounds:
  c:
    max: 0.3
    min: -0.3
  t0:
    max: 59000.0
    min: 58000.0
  x0:
    max: -2.6 # for some reason setting this too low makes the sampler crash
    min: -5.0
  x1:
    max: 4.0
    min: -4.0
  z:
    max: 0.2
    min: 0.001
